/**
 * All user-facing copy. Italian is the default — it is an Italian game — with
 * an English map alongside, so switching the whole UI is a one-line change to
 * `LANG` below.
 */

const it = {
  appTitle: 'Briscola',
  tagline: 'Da 2 a 4 giocatori, direttamente tra i browser.',

  playOnline: 'Gioca online',
  playAi: 'Contro il computer',
  playHotseat: 'Stesso dispositivo',
  playOnlineHint: 'Crea un tavolo e invita con un codice',
  playAiHint: 'Allenati, i posti liberi li gioca il computer',
  playHotseatHint: 'Tutti sullo stesso schermo, a turno',

  createRoom: 'Crea partita',
  joinRoom: 'Entra con codice',
  roomCodeLabel: 'Codice partita',
  roomCodePlaceholder: 'ABC234',
  yourCode: 'Il tuo codice',
  shareCode: 'Condividi questo codice con il tuo avversario',
  copy: 'Copia',
  copied: 'Copiato',
  join: 'Entra',
  back: 'Indietro',
  invalidCode: 'Codice non valido',
  connecting: 'Connessione in corso…',
  waitingOpponent: 'In attesa dell’avversario…',
  opponentLeft: 'L’avversario si è disconnesso',
  partner: 'Compagno',
  botName: 'Computer',
  awaitingShort: 'Assente',
  awaitingPlayer: 'Giocatore disconnesso',
  awaitingHint: 'Aspettiamo che torni. Se non torna, gioca il computer.',
  seatTakenByAi: 'Il computer gioca al suo posto',
  seatingTitle: 'In attesa dei giocatori',
  seatingBody: (missing: number, total: number) =>
    missing === 1
      ? `Manca 1 giocatore su ${total}. Condividi il codice.`
      : `Mancano ${missing} giocatori su ${total}. Condividi il codice.`,
  fillWithBots: 'Riempi con il computer',
  roomFull: 'Partita al completo',
  roomFullHint: 'Tutti i posti a questo tavolo sono occupati.',

  you: 'Tu',
  opponent: 'Avversario',
  player: (n: number) => `Giocatore ${n}`,
  yourTurn: 'Tocca a te',
  opponentTurn: 'Tocca all’avversario',
  seatTurn: (who: string) => `Tocca a ${who}`,
  us: 'Noi',
  them: 'Loro',
  setupSummary: (players: number, extra: string) =>
    `${players} giocatori · ${extra}`,
  points: 'Punti',
  briscola: 'Briscola',
  deck: 'Mazzo',
  turnsLeft: (n: number): string => (n === 1 ? 'mano' : 'mani'),
  lastTrick: 'Mano precedente',
  wonTrick: 'Presa',
  lostTrick: 'Persa',
  sendReaction: 'Invia',
  soundboard: 'Effetti sonori',
  mute: 'Silenzia',
  deckShared: 'Vale per entrambi i giocatori',
  matchScore: 'Partita',
  handNumber: (n: number) => `Mano ${n}`,
  nextHand: 'Prossima mano',
  newMatch: 'Nuova partita',
  matchWon: 'Hai vinto la partita!',
  matchLost: 'Hai perso la partita',
  matchDraw: 'Partita pari',
  handWon: 'Mano tua',
  handLost: 'Mano loro',
  yourName: 'Il tuo nome',
  yourNameHint: 'Come ti vedono gli altri al tavolo',
  namePlaceholder: 'Senza nome',
  difficulty: 'Difficoltà',
  difficultyHint: 'Quanto giocano bene i posti del computer',
  diffEasy: 'Facile',
  diffNormal: 'Normale',
  diffHard: 'Difficile',
  format: 'Formato partita',
  formatHint: 'Quante mani decidono la partita',
  players: 'Giocatori',
  playersHint: 'I posti liberi vengono giocati dal computer',
  seats: (n: number) => `${n} giocatori`,
  settings: 'Impostazioni',
  settingsHint: 'Valgono per questa partita',
  pace: 'Ritmo di gioco',
  paceHint: 'Quanto restano scoperte le carte dopo ogni mano',
  cardStyle: 'Mazzo di carte',
  cardStyleHint: 'Vale per entrambi i giocatori',
  cardsLeft: (n: number) => (n === 1 ? '1 carta' : `${n} carte`),
  lastCards: 'Ultime mani',

  handoffTitle: 'Passa il dispositivo',
  handoffBody: (n: number) => `Tocca a Giocatore ${n}`,
  handoffAction: 'Sono pronto',

  youWin: 'Hai vinto!',
  youLose: 'Hai perso',
  draw: 'Pareggio',
  playerWins: (n: number) => `Vince Giocatore ${n}`,
  finalScore: 'Punteggio finale',
  rematch: 'Rivincita',
  leave: 'Esci',

  rulesTitle: 'Regole in breve',
  rules: [
    'Mazzo da 40 carte. Vince chi supera i 60 punti su 120.',
    'Ordine di presa: Asso, 3, Re, Cavallo, Fante, 7, 6, 5, 4, 2.',
    'Punti: Asso 11, Tre 10, Re 4, Cavallo 3, Fante 2. Le altre valgono 0.',
    'Non c’è obbligo di rispondere al seme: puoi giocare qualsiasi carta.',
    'La briscola batte ogni altro seme. A parità di seme vince la carta più alta.',
    'Chi vince la mano pesca per primo e gioca la mano successiva.',
  ],
}

const en: typeof it = {
  appTitle: 'Briscola',
  tagline: '2 to 4 players, straight between the browsers.',

  playOnline: 'Play online',
  playAi: 'Play the computer',
  playHotseat: 'Same device',
  playOnlineHint: 'Open a table and invite with a code',
  playAiHint: 'Practise — the computer plays any empty seats',
  playHotseatHint: 'Everyone on one screen, taking turns',

  createRoom: 'Create game',
  joinRoom: 'Join with code',
  roomCodeLabel: 'Game code',
  roomCodePlaceholder: 'ABC234',
  yourCode: 'Your code',
  shareCode: 'Share this code with your opponent',
  copy: 'Copy',
  copied: 'Copied',
  join: 'Join',
  back: 'Back',
  invalidCode: 'Invalid code',
  connecting: 'Connecting…',
  waitingOpponent: 'Waiting for opponent…',
  opponentLeft: 'Your opponent disconnected',
  partner: 'Partner',
  botName: 'Computer',
  awaitingShort: 'Away',
  awaitingPlayer: 'Player disconnected',
  awaitingHint: 'Waiting for them to come back. If they don’t, the computer takes over.',
  seatTakenByAi: 'The computer is playing their seat',
  seatingTitle: 'Waiting for players',
  seatingBody: (missing: number, total: number) =>
    missing === 1
      ? `1 more player needed of ${total}. Share the code.`
      : `${missing} more players needed of ${total}. Share the code.`,
  fillWithBots: 'Fill with computer',
  roomFull: 'Table is full',
  roomFullHint: 'Every seat at this table is taken.',

  you: 'You',
  opponent: 'Opponent',
  player: (n: number) => `Player ${n}`,
  yourTurn: 'Your turn',
  opponentTurn: 'Opponent’s turn',
  seatTurn: (who: string) => `${who} to play`,
  us: 'Us',
  them: 'Them',
  setupSummary: (players: number, extra: string) =>
    `${players} players · ${extra}`,
  points: 'Points',
  briscola: 'Trump',
  deck: 'Deck',
  turnsLeft: (n: number) => (n === 1 ? 'trick' : 'tricks'),
  lastTrick: 'Previous trick',
  wonTrick: 'Won',
  lostTrick: 'Lost',
  sendReaction: 'Send',
  soundboard: 'Sound effects',
  mute: 'Mute',
  deckShared: 'Applies to both players',
  matchScore: 'Match',
  handNumber: (n: number) => `Hand ${n}`,
  nextHand: 'Next hand',
  newMatch: 'New match',
  matchWon: 'You win the match!',
  matchLost: 'You lose the match',
  matchDraw: 'Match drawn',
  handWon: 'Hand won',
  handLost: 'Hand lost',
  yourName: 'Your name',
  yourNameHint: 'How the others see you at the table',
  namePlaceholder: 'Unnamed',
  difficulty: 'Difficulty',
  difficultyHint: 'How well the computer seats play',
  diffEasy: 'Easy',
  diffNormal: 'Normal',
  diffHard: 'Hard',
  format: 'Match format',
  formatHint: 'How many hands decide the partita',
  players: 'Players',
  playersHint: 'Empty seats are played by the computer',
  seats: (n: number) => `${n} players`,
  settings: 'Settings',
  settingsHint: 'Apply to this match',
  pace: 'Pace',
  paceHint: 'How long cards stay face-up after each trick',
  cardStyle: 'Card deck',
  cardStyleHint: 'Applies to both players',
  cardsLeft: (n: number) => (n === 1 ? '1 card' : `${n} cards`),
  lastCards: 'Final tricks',

  handoffTitle: 'Pass the device',
  handoffBody: (n: number) => `Player ${n}'s turn`,
  handoffAction: 'I’m ready',

  youWin: 'You win!',
  youLose: 'You lose',
  draw: 'Draw',
  playerWins: (n: number) => `Player ${n} wins`,
  finalScore: 'Final score',
  rematch: 'Rematch',
  leave: 'Leave',

  rulesTitle: 'Rules at a glance',
  rules: [
    '40-card deck. Take more than 60 of the 120 points to win.',
    'Trick order: Ace, 3, King, Knight, Jack, 7, 6, 5, 4, 2.',
    'Points: Ace 11, Three 10, King 4, Knight 3, Jack 2. Everything else 0.',
    'No obligation to follow suit — you may play any card.',
    'Trump beats any other suit. Within a suit, the stronger card wins.',
    'The winner of a trick draws first and leads the next one.',
  ],
}

const LANG: 'it' | 'en' = 'it'

export const t = LANG === 'it' ? it : en
